{{ include "common.deployment" (dict "top" . "deployment" .Values.mainDeployment) }}
---
{{ include "common.service" (dict "top" . "service" .Values.service) }}
---
{{ include "common.hpa" (dict "top" . "hpa" .Values.hpa) }}
---
{{ include "common.gateway" (dict "top" . "gateway" .Values.gateway) }}
---
{{ include "common.vs" (dict "top" . "vs" .Values.vs) }}